### ISSUE TITLE
[BUG] Can't create a wallet

### ISSUE THREAD

**Issue by longgamma-massa** [massalabs/thyra#142]
**Setup:**
Ran Thyra server on Macbook Pro (Apple M1 Pro) // OS: Monterey (12.6) // Browser: Chrome

**Steps to reproduce:**

1. Entered Nickname
2. Entered Password
3. Click on Add: producec no Action.

**Solved by:**
Stopping the server and running it again. 

NOTE:
I had bunch of difficulties with the Installation process that were recorded by @thomas-senechal. Maybe the bug is related to it.

**Comment by thomas-senechal** [comment]
Just a few more details:
- @longgamma-massa got that bug using [v0.0.2](https://github.com/massalabs/thyra/releases/tag/v0.0.2).
- I also got that bug but using the `main` branch (https://github.com/massalabs/thyra/commit/d80abe2ebff6eb6fe1aa3064e42090acfb54bd69) and it also got fixed by restarting the server.
- The "fix" (restarting the server) was provided by @Trottoir .

So, this bug doesn't seems to be related to the installation process. Unless @Trottoir has more details about this bug, we should check if it also happens on the other platforms and architectures.

**Comment by SlnPons** [comment]
@Thykof did you experience the same thing? 
@thomas-senechal, @Trottoir any idea how about why this is happening? How are we going to test the product is there is the 'problem' occurring?

**Comment by gregLibert** [comment]
We need to stop writing wallet in the same directory as the binary. We should use standard one such as ~/.config/massa/ on Linux.

Furthermore, we need to catch errors and screen them out to users in the browser (and not the console...)

**Comment by thomas-senechal** [comment]
> We need to stop writing wallet in the same directory as the binary. We should use standard one such as ~/.config/massa/ on Linux.

If I'm not wrong, `~/.config/` also exist on MacOS. But i don't think `~` exists on Windows. But we could use `$HOME` instead, which is compatible with Linux, MacOS and Windows.

**Comment by SlnPons** [comment]
Our assumption is that this bug is due to: https://github.com/massalabs/thyra/issues/203

However, we still need to address Greg's comment and separate the wallet file from the binary directory.
See here: https://github.com/massalabs/thyra/issues/214

**Comment by thomas-senechal** [comment]
@SlnPons I think we can close this issue since #203 has been merged and Greg's comment is being adressed in another issue.
