### ISSUE TITLE
Testing Smart Contract - Simulator

### ISSUE THREAD

**Issue by ASAPSegfault** [massalabs/thyra#143]
- [ ]  Test, improve simulator
- [ ]  Document how to use it
- [ ]  Add simulator to our procedures and CI practice if it makes sens

**Comment by qdrn** [comment]
Related https://github.com/massalabs/massa-sc-tester

**Comment by Trottoir** [comment]
Hey guys, just have a 10 min call ( efficiency 🚀) with @Eitu33 ( the GOAT ) about the way the Simulator is working as we need it for two of our "Features".

We had some unknow about : 
- How to launch it ? 
- What's the input of the simulation ? 
- What's the output of the simulation ? 
- How to import it ?

Has been answered : 
- How to launch it ? => For testing purpose I'm testing it directly through rust cargo command
- What's the input of the simulation ? => A ledger.json file, we know the interface contract of it now
- What's the output of the simulation ? => The ledger.json modified & the trace.json for events & logs call
- How to import it ? => Thomas will handle the .wasm generation in a next commit in order to be able to include it in an js project

**Comment by Trottoir** [comment]
Issue mooved here https://github.com/massalabs/massa-sc-toolkit/issues/2

**Comment by Eitu33** [comment]
> What's the input of the simulation ? => A ledger.json file, we know the interface contract of it now

Don't forget about the `execution_config.json` as well.

`execution_config.json` => input
`trace.json` => output
`ledger.json` => input and output
