### ISSUE TITLE
Innonet Outage Monitoring

### ISSUE THREAD

**Issue by ASAPSegfault** [massalabs/thyra#181]
As Massa's ecosystem keeps expanding, we need to ensure we can monitor innonets statuses.

Currently when innonet is down, a Github Action mechanism gets triggered. This mechanisms needs to be checked and corrected as it currently create issues in Thyra's Github even in the event of a false positive (innonet is up but an issue is created nonetheless).

- [x] Identify the root cause of the false positives
- [ ] Determine what is the best way to assess an outage and implement it.

Outage assessment's process example :
- Make sure we can access the outside world (ping google.com)
- If this checks, ping innonet's address a few times
- If at least one ping returns data, we're not in the case of an outage and thus we musn't send notifications nor create an issue in Thyra's Github
- However, if ping commands doesn't return data, the outage is real and we must create an issue

**Comment by thomas-senechal** [comment]
As explained [here](https://github.com/upptime/upptime/discussions/492#discussioncomment-1859058
), `Upptime` does close and delete issues that are supposed to be false positives. 

But as I explained in https://github.com/massalabs/website-status/issues/11 , since we are using the CI `GITHUB_TOKEN` instead of a [`Personal Access Token`](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) and created issues are [locked](https://docs.github.com/en/communities/moderating-comments-and-conversations/locking-conversations), `Upptime` can't close the issue nor delete it. 

I will see if it's possible to allow the CI to comment, close and delete issues using the `GITHUB_TOKEN`.

**Comment by thomas-senechal** [comment]
It looks like it's not possible to use the `GITHUB_TOKEN` to close a locked issue and a [`Personal Access Token`](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) of an account with suffisant permissions is required.

Furthermore, using a [`Personal Access Token`](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) or find a way to keep using the `GITHUB_TOKEN` won't fix the false positive issue since, if we add assignees with an issue is created by `Upptime`, those assignees will still get notified.

**Comment by thomas-senechal** [comment]
When `Upptime` fail to ping a website, it will retry 3 times. [Here](https://github.com/upptime/uptime-monitor/blob/561b61a8cb17f3f09be23ce079842345d671b131/src/update.ts#L260) is the code doing the retries.
This code is here to ensure that it is not a false positive. 

For example: 
The 2nd of October, around 8:57pm CEST, all the innonets website went down at the same time as you can see [here](https://github.com/massalabs/website-status/actions/runs/3169705739/jobs/5161800198#step:3:24). The [previous CI](https://github.com/massalabs/website-status/actions/runs/3169646390/jobs/5161699946) ran at 8:33pm CEST and didn't had any issue, and [the next one](https://github.com/massalabs/website-status/actions/runs/3169764611/jobs/5161897593) at 9:13 CEST said all innonets were back up. 
In the CI saying that innonets websites are down, we can see that each websites [got pinged 3 times](https://github.com/massalabs/website-status/actions/runs/3169705739/jobs/5161800198#step:3:22).
Since `massa.net` was still up, we can guess that the innonets were down, or at least unaccessible and so, that it wasn't a false positive.

**Comment by thomas-senechal** [comment]
Seeing how `Upptime` is made, it is not possible to increase the number of retries, nor increase the amount of time between tries, nor modifying the code of `Upptime` to increase those numbers. 

Since `Upptime` already includes a retry system, as explained in [that comment](https://github.com/massalabs/thyra/issues/181#issuecomment-1273236373), I think we should stick with it for now and if we need something more robust for a product in production, we might want to change for another tool or service.

@SlnPons What do you think about that ?

**Comment by SlnPons** [comment]
@thomas-senechal thanks for checking and sharing this. 
* The end goal of this issue is to enable the Inno team to be the first ones to know when InnoNets are down. By somehow sending something to someone (some-x to be defined thanks to this issue).
* Based on your research, your conclusion is that what we use now is optimal.
* So my question for you is: Can we prevent the team from receiving false positive alerts? (sorry it's not 100% clear on your comments)

**Comment by thomas-senechal** [comment]
@SlnPons 
> If we do have too many false positive notifications (too many = more than 3) 

I think we should define a time to that number of false positive. If it's 3 per weeks, per month, on 6 months etc.
I think a realistic number of allowed false positive is 2 per months, and so if a 3rd one occurs, we will search for better tooling. 

Note that it might take time to know if it's a false positive or not, especially if we don't check it directly when the incident occurs.

**Comment by SlnPons** [comment]
Very good point! 
Do you agree guys? @ASAPSegfault @gregLibert @Thykof @Trottoir @SebastienValla 
Summary of the suggestion: 
* We need to be the first ones to know when InnoNets are down so we can correct it. For that, we're suggesting to send notifications each time GitHub actions get triggered.
* But we were under the impression that the current Github process was triggering too many false positive which, of course, we want to avoid!
* In the comments above you have all the details, but the conclusion is that what we have now is good enough based on our current constraints to maintain InnoNets up (officially none) as well as our needs (=send notification). We have no reason to spend more time on this right now.
==> So let's move with the existing process, add notifications to it AND identify false positive on the fly. If we have more than 2 per month, we should raise it and revisit the process and potentially tooling. If we have less, we'll keep using it as is.

**Comment by Thykof** [comment]
it's ok for me, let's move forward. In addition, there are very great tools like datadog, newrelic for monitoring applications. 
Also a really simple tool: uptime robot: https://uptimerobot.com/ easy to set up for email notification.

**Comment by ASAPSegfault** [comment]
Works for me.
Let's focus on the notifications, we will change our process later if/when required.

**Comment by thomas-senechal** [comment]
I close this issue since it's solved by the decision we took to keep the status monitoring we already have. 
https://github.com/massalabs/thyra/issues/182 is the continuity of this issue, which implies to search whom must be assigned to the incidents and implement the modifications in the status monitoring to make sure it assigns those people when an incident occurs.
