### ISSUE TITLE
Send email or notification when Innonet is down

### ISSUE THREAD

**Issue by ASAPSegfault** [massalabs/thyra#182]
As Massa's ecosystem keeps expanding, we need to ensure we can send notifications when Innonet is down.

- [ ] Forward a notification through email or discord when an issue about outage is created on Github.
- [ ] Write a procedure listing all the steps that need to be checked in order to deal with the matter for the person who receives the notification.

OLD :

- [ ] Identify who should receive the notifications
- [ ] Identify what’s possible in term of notification process and how to share them using the simplest solution available 
- [ ] Implement the solution

Example :
- Github notifications gets created when an outage issue has been created
- Forward this notification to another app (dedicated Discord's channel for example), allowing the team to be aware of the problem in an automated fashion whithout having to check Github

**Comment by thomas-senechal** [comment]
I think that when a website of the innonet is down, we need to check a few things:
1. What is the error in the Github Action to make sure that the error doesn't come from the Github Action or the Github Runner.
2. Check if the issue doesn't come from the Domain or servers provider.
3. Check if the server is still up.
4. Connect to the server to check what's happening.

I think that 1 & 2 can be done by anybody from Massa since it doesn't requires any specific access. Since we are only talking about monitoring the innonets web sites, that person should be from the Inno Team IMO.
But 3 requires the IP address of the server and not everybody has it, and 4 requires the credentials to connect to the server, and so, only a few people can do it. 

@gregLibert @SlnPons Do you think I missed something in my list of things to check ? If so, which ones and in your opinion, who is able to perform those checks ? Do you have some ideas about who could perform all those checks when an incident occurs ?

**Comment by SlnPons** [comment]
@thomas-senechal nice list. Couple of questions:
* step 1 - what would it mean if the error if coming from GitHub actions or github runner?
* same question for step 2.
* I'm trying to identify how we could identify false positive. IE: "if step 1 and 2 are KO then it's a false positive and you can close the issue." So we can write a clear and simple procedure for everyone to follow. 

As for whom will receive the notification, if it's just a question of credentials it's easy to share across the team. Are you sure there is no specific skills to have to be able to do that? (Inno team = pm & devs)

**Comment by thomas-senechal** [comment]
> step 1 - what would it mean if the error if coming from GitHub actions or github runner?

That means that we should check if the down website it accessible (using a web browser or an http request using `curl` or `Postman` for example), if the website is up, rerun the Github Workflow to make see if the issue is solved since it might be a false positive because of a bad Github Runner or another issue related to Github. If it's still not working, it might be necessary to check the Status Page of Github to check if there is an incident.



> same question for step 2.

The Domain or server provider might have an incident or a maintenance, so we need to check if they do and if so, note it in a comment to keep everybody updated (if our providers aren't something that must be kept secret?). 



> I'm trying to identify how we could identify false positive. IE: "if step 1 and 2 are KO then it's a false positive and you can close the issue."
IMO, only the step 1 can be a false positive. If the issue is due to an update, an incident, or a maintenance of Github, it's not a false positive. If the issue is related to a Github runner, it is a false positive, but it shouldn't happen often.

Furthermore, I think that the assignee should post a comment in the issue to keep everybody updated that we have an idea of where the incident come from and that we are working on it to fix it as soon as possible. `Upptime` will automatically display those comments in the website view.


> As for whom will receive the notification, if it's just a question of credentials it's easy to share across the team. 

Some credentials, such as the ones to connect on a server, cannot be shared with all the team members since it increases the security risks. So I'm not sure it's possible to take anybody from the team to do step 4. 


> Are you sure there is no specific skills to have to be able to do that? (Inno team = pm & devs)

You are right, I think it should be a dev of the Inno team because it does require some knowledge about the Github Actions for step 1. Step 2 can be done by anybody since it's basically watching on a status page if there is an incident occurring, but since PMs probably don't have the knowledge to do the step 1, I think it's better to assign some devs.

**Comment by gregLibert** [comment]
>@gregLibert @SlnPons Do you think I missed something in my list of things to check ? If so, which ones and in your opinion, who is able to perform those checks ? Do you have some ideas about who could perform all those checks when an incident occurs ?

We should do things simply:
- when receiving an incident, we simply check that the website is operational by connecting to the different URLs (procedure to create).
  * if it works => the issue is closed
  * If not, we assign the issue to a developer who has access rights to the server to investigate.

**Comment by thomas-senechal** [comment]
> We should do things simply...

I agree with you @gregLibert . But in your opinion, who should be assigned to the created issues at the beginning ?

**Comment by SlnPons** [comment]
Due to other priorities, this ticket has been pushed back. And so it will be back in the To Do column. 
Hugo started working on it if you need some context; however everything that has to be done is written: 
* In this page regarding the assignees to put in place: https://upptime.js.org/docs/configuration/#assignees
* In that page regarding how to send the notifications: https://upptime.js.org/docs/notifications
* Finally, a nota bene, to achieve this ticket you need to work hand-to-hand with a discord admin (to set up the notification correctly).

Between the info above and the info in the issue's description, you've got all context to do it :)

**Comment by SlnPons** [comment]
Innonets have been closed so this issue is not relevant anymore
