### ISSUE TITLE
Website registry link does not take the thyra running port into account

### ISSUE THREAD

**Issue by peterjah** [massalabs/thyra#280]
For example if i run thyra with "-http-port 8080"
the xflappy url should be
```http://xflappy.massa:8080/```
instead of
```http://xflappy.massa/```

**Comment by SlnPons** [comment]
Why is that important? Not sure to understand :/ 
Also, can you confirm that this can be done now as it touches thyra itself and no "functionalities" that will be transformed into plug-in?

**Comment by thomas-senechal** [comment]
> Why is that important? Not sure to understand :/ Also, can you confirm that this can be done now as it touches thyra itself and no "functionalities" that will be transformed into plug-in?

I checked and the changes required to fix this issue will not touch anything related to plugins. 
We just have to modify how we make `.massa` `urls` in the `Webcreator` and `Registry` pages.

**Comment by SlnPons** [comment]
Hey @thomas-senechal could you explain me how to test this please? :)

**Comment by thomas-senechal** [comment]
> Hey @thomas-senechal could you explain me how to test this please? :)

Hi @SlnPons ! 
As explained in the description, the issue was that, while you run Thyra on a different port using the `--http-port` option, the website you opened where not accessible because we opened the links on the default port. 
In the example in the description, Thyra is running on port `8080`. But when the user tries to open a website, we opened it with the following URL: `http://xflappy.massa/` which resulted in an error since Thyra is running on `8080`. We needed to open the website using the following URL to make it work: `http://xflappy.massa:8080/`.

So, to test the fix, I think you should do it in 2 times. First, check if Thyra is running normally by running `thyra-server`. Go to the registry page, and open a website and see if everything is working well.
Then, you should run `thyra-server` with the `--http-port` option. For example:
```
thyra-server --http-port 8080
```
Thyra should be accessible on `http://my.massa:8080/thyra/registry`. Once you are on the page, open a website and check that it is working and that the URL is `http://XYZ.massa:8080/`, with `XYZ` being the name of the website.

You can check if everything is working fine with other ports too, you just have to make sure to replace the port in the URLs. 

I'm still available if you have any question 👋

**Comment by SlnPons** [comment]
Hey @thomas-senechal  thanks a lot for your explanations. Very clear. 
I just tested with port 8080 as described and it is NOT working on my side. 
This is what I experienced: 
1. normal behaviours with `thyra-server` running on default port (ie: can access thyra/registry + any websites)
2. Running thyra on port 8080 using your cmd line
3. Can access thyra normally (see screenshot) 


![Image](https://user-images.githubusercontent.com/109611779/209656376-2577fec5-7512-467d-86c0-75c591b80871.png)


4. Failing at accessing a website listed on the registry page (see screenshot) 


![Image](https://user-images.githubusercontent.com/109611779/209656446-de85219a-109b-46c2-a26c-6e59fe250395.png)

(ps: I tried with another port ex: 1234 and same behaviour, thyra is accessible but no website is)

**Comment by SlnPons** [comment]
After checking with @thomas-senechal, the error I experienced was due to the version of thyra I was using (thyra install with the install script instead of thyra install with Go). 

Now that I have tested with thyra install with Go, everything is working well. 
Thanks again Thomas :) :)
