### ISSUE TITLE
🔥 Testnet17 - Registry page site order

### ISSUE THREAD

**Issue by SlnPons** [massalabs/thyra#327]
**Describe the bug**
The websites on the registry page are ordered randomly. They should be ordered alphabetically.

**To Reproduce**

1. Go to the registry page
2. See the order: random

**Expected behavior**
The websites should be ordered alphabetically.

**Screenshots**
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/109611779/206159009-f5ca30d1-17a1-4ea5-bb59-440e4ca16ffd.png">

**Thyra version**
Testnet 17 branch #310 

**Desktop (please complete the following information):**
 - OS: MacOS

**Additional context**
It was ordered alphabetically on testnet 16 and innonet 15 if it helps to identify the problem.

**Comment by gregLibert** [comment]
@B-Naoufal where is the PR linked to this issue ?

**Comment by SlnPons** [comment]
@gregLibert it's in the big PR #310 I believe

**Comment by B-Naoufal** [comment]
since i was working on this PR https://github.com/massalabs/thyra/pull/317#pullrequestreview-1208991322, and all the recent changes needed as perquisite , i pushed my modifications for this issue in the same PR, here is the commit : https://github.com/massalabs/thyra/pull/317/commits/2d1cde21325a21bad6bf6e0e9cbfff6625cffaec @gregLibert

**Comment by B-Naoufal** [comment]
True @gregLibert ; Resolved in https://github.com/massalabs/thyra/commit/2d1cde21325a21bad6bf6e0e9cbfff6625cffaec
