### ISSUE TITLE
The page with 'Node manager plugin' does not open

### ISSUE THREAD

**Issue by bombermine3** [massalabs/thyra#440]
**Describe the bug**

The installer ends with the message:
[WinError 5] Access is denied: 'mkcert.exe'

Thyra app does not appear in the system tray. Launched it manually. Successfully opened the link 'http://my.massa/thyra/wallet/index.html' and created a wallet. When I go to 'Node manager plugin' page I get redirect to 'my.massa:4222' and 'my.massa refused to connect.' message

**To Reproduce**

1. Install Thyra 
2. Open 'http://my.massa/thyra/wallet/index.html'
3. Press 'Node manager plugin'

**Expected behavior**
The page with the Node manager should open

**Screenshots**
<img width="658" alt="Screenshot 2023-02-03 at 11 21 38" src="https://user-images.githubusercontent.com/84911882/216553584-888e7c15-c2e4-4385-9bdb-4c8e19f5301b.png">
<img width="1031" alt="Screenshot 2023-02-03 at 11 50 34" src="https://user-images.githubusercontent.com/84911882/216554594-f748f932-350a-4ee0-bec3-8da88a7c5498.png">

**Thyra version**
Latest version from github. The exact version is not specified

**Desktop (please complete the following information):**
- OS: Windows 11
 - Browser Chrome 109.0.5414.120

**Additional context**

**Comment by thomas-senechal** [comment]
Hi @bombermine3 ! 

We tried to reproduce your issue but couldn't reproduce your problem. 
It looks like you have 2 issues, the node manager not being accessible, and the `Access is denied: 'mkcert.exe'` error.
I think this might be related to an antivirus deleting/blocking those binaries. 

Do you have an antivirus installed on your computer ? If so, could you check if there is an error related to `mkcert.exe` or `node-manager-plugin.exe` ?

Could you restart Thyra and check if the node manager is running properly ? 
Could you also send in a comment a screenshot of the thyra-server logs ? 

Thanks a lot !

**Comment by bombermine3** [comment]
Hi!

 Yes, those seem to be two different problems. 

As for the first one, related to mkcert.exe, the file runs normally manually.
<img width="823" alt="Screenshot 2023-02-06 at 15 35 26" src="https://user-images.githubusercontent.com/84911882/216973636-39ff7282-50e2-4577-97e8-f064be2c3cb5.png">

The second problem is due to the fact that the server listens to port 4200, and the redirect occurs on port 4222.
<img width="1117" alt="Screenshot 2023-02-06 at 15 35 44" src="https://user-images.githubusercontent.com/84911882/216973987-5162bc08-0156-422d-ae11-55d46d841196.png">
 
I run Thyra on a virtual machine and there is no antivirus

**Comment by thomas-senechal** [comment]
Thanks a lot for your reply ! 

> As for the first one, related to mkcert.exe, the file runs normally manually. <img alt="Screenshot 2023-02-06 at 15 35 26" width="823" src="https://user-images.githubusercontent.com/84911882/216973636-39ff7282-50e2-4577-97e8-f064be2c3cb5.png">

Could you try to relaunch the installer now ? Just to know if the mkcert error got somehow fixed ?

> The second problem is due to the fact that the server listens to port 4200, and the redirect occurs on port 4222. <img alt="Screenshot 2023-02-06 at 15 35 44" width="1117" src="https://user-images.githubusercontent.com/84911882/216973987-5162bc08-0156-422d-ae11-55d46d841196.png">
> 
> The page actually opens when you specify the correct port in the address bar. <img alt="Screenshot 2023-02-06 at 15 43 53" width="1036" src="https://user-images.githubusercontent.com/84911882/216974778-2272e426-f852-4cd5-a028-5c2b8ebfa67d.png">

About the node manager, for now, we are "force installing" it at each Thyra start. Right after the install, we start the node manager on the port 4222 to make sure it wont interfere with the other installed plugins. During next Thyra starts, the plugin will start normaly, usually on port 4200 except if you have other plugins installed. 
So I think you start Thyra a first time, opened the wallet page, and then, restarted thyra but didn't refreshed the page. And that's why Thyra redirected you to the port 4222. 

Notes that this kind of issue is already known and that we are already working on it . A fix should be available in a future release of Thyra. 

Could you confirm that everything is working fine after executing the following steps ?
1. Restart Thyra
2. Open http://my.massa/thyra/wallet/index.html
3. Press 'Node manager plugin'
4. The webbrowser opened the Node Manager on the right port (usually 4200 except if you deleted the node manager plugin before restarting Thyra)

**Comment by thomas-senechal** [comment]
> I tried restarting the installer, but the "Access denied" message is still there.
> 
> And yes, I confirm that the port problem is solved as described.

Thanks again ! 
I will keep digging into the `mkcert` issue.

**Comment by SlnPons** [comment]
@thomas-senechal Thanks for your time on this issue. 
@bombermine3 it is hard to reproduce consistently the bug you reported...so we will stop actively working on it but we are starting a re-work of our installation script on the difference OS to make them more robust and so we really hope that this will solve the error you're experience. 
We'll keep you updated for sure :)
