### ISSUE TITLE
Not able to pass coins with Execute Function

### ISSUE THREAD

**Issue by SebastienValla** [massalabs/thyra#443]
**Describe the bug**
When calling a function with execute function with coins, we have a event Context().transferedCoins who do not show the sent coins.
It is working when we do so with massa web3

**To Reproduce**

**Expected behavior**

**Screenshots**

**Thyra version**
The version of Thyra the bug is present in.

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS, Windows...]

**Additional context**

**Comment by SlnPons** [comment]
NB: make sure to use the function of the plug-in wallet and not Thyra wallet please. 
Thyra wallet will be deprecated very soon :)

**Comment by ASAPSegfault** [comment]
This issue is not on Thyra side, which is why I close it. The issue comes from the fact that the transferedCoin function of the sdk returns 0 even if the contract's balance itself get updated properly. 
It will be solved by the core team in testnet 20 : https://github.com/massalabs/massa/issues/3575
