### ISSUE TITLE
Create SET function in Massa-api

### ISSUE THREAD

**Issue by SlnPons** [massalabs/thyra#50]
Create a SET function in Massa-api to allow Thyra to set storage using API instead of a SC.
Same as [get_datastore_entries](https://docs.massa.net/en/latest/technical-doc/api.html#get-datastore-entries) function so that we don't have to create a SC (faster & more secure).

**Comment by SlnPons** [comment]
@damip what do you think?

**Comment by damip** [comment]
Hello @SlnPons  !

We can't just arbitrarily write to the blockchain directly from the API (but we can read !).

To write, we need to emit an new type of operation (let's call it SetData) that will be included in a block etc... like all other operations that write to the blockchain. SetData would contain a datastore to merge into the datastore of the target address.

For obvious security reasons, SetData can't simply write into the datastore of any address, but only to the address of the sender of that operation that has signed it. Since operation senders can only be addresses derived from private keys, SetData won't be able to write to smart contract addresses created by CreateSC.

As a result, I'm afraid we don't want to do that because:
* it won't be faster
* it won't be safer
* it will be limited to acting on addresses we own in our wallet, and therefore not on most smart contract addresses

**Comment by SlnPons** [comment]
Very clear! Thanks for the answer @damip. Will keep looking for a better solution

**Comment by SlnPons** [comment]
Potential solution: https://github.com/massalabs/massa/discussions/2847

**Comment by SlnPons** [comment]
Closing this issue based on the previous comments.
