### ISSUE TITLE
Node Manager installer for MacOs

### ISSUE THREAD

**Issue by peterjah** [massalabs/thyra#513]
**Context**
![image](https://user-images.githubusercontent.com/34547263/223398664-91097fd1-1a00-40f6-aefd-72181945b277.png)

In plugin-manager page, the node-manager install card perform an OS detection in order to get the plugin url corresponding to the target Os.
It seems to work fine but we need to clarify the macOS part because it seems even if target is arm64, the amd64 link is dowloaded and curiously working well.

the code is here:
`web/plugin-manager/src/components/installNodeManager.tsx`

**To do**
On your mac:
Test the both arm64 and amd64 Node manager binaries.
If both are working well maybe we do not need 2 binary here.
If its the case, make the changes in the node manager CI and in Thyra frontend to have only 1 MacOs version.
If we still need 2 versions, check that the Os target + arch is well detected.

Then remove the "for {Os}" from the button assuming the os is well detected, the user does not need this information

**QA testing**
Node manager installation is working for all OS

**Comment by thomas-senechal** [comment]
`It seems to work fine but we need to clarify the macOS part because it seems even if target is arm64, the amd64 link is dowloaded and curiously working well.`

I just tried to download the 2 version on my ARM64 MacBook. I ran the `file` command to get informations about the files and here is what I got:
```sh
$ file thyra-plugin-node-manager_darwin-amd64
thyra-plugin-node-manager_darwin-amd64: Mach-O 64-bit executable x86_64
```
```sh
$ file thyra-plugin-node-manager_darwin-arm64
thyra-plugin-node-manager_darwin-arm64: Mach-O 64-bit executable arm64
```

And I was able to run the `amd64` version.

Then, I checked for the binary installed by the Plugin Manager and here is the result:
```sh
$ file thyra-plugin-node-manager_darwin-amd64
thyra-plugin-node-manager_darwin-amd64: Mach-O 64-bit executable x86_64
```
I think it's because Apple Silicon Macs has a "translation" system built in that allows them to run `amd64` code by, "translating" the binaries to `arm64` binaries to then be able to run them.

That's why even if we install the `amd64` version from the Plugin Manager, we are still able to run it.

IMHO, we should fix the bug in the Plugin Manager frontend and keep both versions. The `amd64` version is mandatory for people still running Intel powered Macs since they don't have the same "translation" system to run `arm64` binaries. And `arm64` seems to be the only available architecture for new Macs. Removing this binary would make us lose time later because we would have to readd it, and it would also be a lost in performances due to the "translation" system.

**Comment by SlnPons** [comment]
This should be solved by the detecting the OS using the back-end instead of the front-end. 
Is that correct @0xMazout? 

cc @peterjah

**Comment by 0xMazout** [comment]
Yes but for now it's not handled didn't have time to do it for the moment .

**Comment by 0xMazout** [comment]
We have solved this by making the detection in the backend .
And sending only one link to the specified OS detected
