### ISSUE TITLE
Wallet created in Thyra on Ubuntu lost on the frontend after page refresh 

### ISSUE THREAD

**Issue by Pierregvx** [massalabs/thyra#524]
**The problem(s)**
When I create a wallet using the wallet page in Thyra version 0.1.10 on Ubuntu, the wallet is lost when I refresh the page or navigate to a new page.

**To Reproduce**
1. Launch Thyra on Ubuntu
2. Navigate to the wallet page
3. Create a new wallet by following the steps provided
4. Verify that the wallet has been successfully created and is visible on the wallet page
5. Refresh the page or navigate to a different page
6. Observe that the wallet is no longer present on the wallet page

**Expected behavior(s)**
I expect that any wallets created using the wallet page will persist even when the page is refreshed or navigated away from.

**Screenshots**

**Thyra version**
The issue is present in Thyra version 0.1.10.

**Desktop**
- OS: Ubuntu.

**Comment by SlnPons** [comment]
@Pierregvx the only way I could reproduce your bug is when I had wallet create on testnet 19 and trying to create a new one on testnet 20. 
As the address format changed, it causes a bug that prevent the new wallet from being created, and the current poor UX and error management prevent you from knowing this. 

This issue should be solved by removing "old" (on testnet 19 and prior) created wallet. ⚠️ These wallets need to be deleted manually from your computer in your user/bin/thyra. 
let me know if it solved your problem

**Comment by Pierregvx** [comment]
yes it's working now
