### ISSUE TITLE
MacOs installer: Can't check for malicious 

### ISSUE THREAD

**Issue by Thykof** [massalabs/thyra#535]
**The problem(s)**

I can't run the installer

**To Reproduce**

download https://github.com/massalabs/thyra/releases/download/v0.1.11/thyra-installer_darwin_amd64

double click

**Expected behavior(s)**

**Screenshots**

<img width="268" alt="image" src="https://user-images.githubusercontent.com/11590067/224750017-89bf0395-4b25-4531-8083-10e9c01bcb53.png">

**Thyra version**
The version of Thyra the bug is present in.

https://github.com/massalabs/thyra/releases/tag/v0.1.11

**Desktop (please complete the following information):**
 - OS: MacOS M1
 
 **Any other useful info**

**Comment by thomas-senechal** [comment]
Hi @Thykof , 

This issue is well known but we can't fix it for now. A workaround is to start the installer from `Finder`. Right click on the installer and click on `Open`. A popup will tell you something like "This app is from an unidentified developper, do you really want to open it ?", click on the `Open` button and the installer should start running.

**Comment by Thykof** [comment]
thanks, we should add this procedure in https://github.com/massalabs/thyra/pull/518
