### ISSUE TITLE
Thyra installer problem

### ISSUE THREAD

**Issue by labranche** [massalabs/thyra#602]
Hi,
I'm trying to run a node throught THYRA but when I run the install i get this error :
root        : ERROR    Command failed with error : /bin/sh: brew: command not found

So I have install homebrew but without any changes ...

Can somebody help me please ?
Thanks.

**Comment by SlnPons** [comment]
Hey @labranche! Sorry for the inconvenience :/ 

It seems that homebrew is not installed correctly on your machine and that's why you're having such a message... If you are comfortable with your terminal, could you run the following command please ? `where brew` 
Like this we'll see if homebrew is well installed and where to unblock you the best we can. Cheers

**Comment by SlnPons** [comment]
Closing this issue as I don't have any answer. But please feel free to re-open it when you have time to give answer my questions :)
