### ISSUE TITLE
[INVEST] - Explore one click install for multiplatform

### ISSUE THREAD

**Issue by Trottoir** [massalabs/thyra#83]
AS IS : 
- The user needs to install dependencies & libraries such as go, DNS and potentially a C++ compiler for GUI.

TO BE : 

- The installation of dependencies & libraries is done on a one click install

**Comment by SlnPons** [comment]
Objectifs du ticket: 
1. List all current needed steps to install Thyra the listed platform below so that we can make sure we haven't missed sth:
a. MacOs Catalina & Monterey
b. Linux Ubuntu
c. Windows 11
2. Explore the existing libraries we can use to install those steps automatically
- ask yourself the question: what happens if user already has one of these steps on his machine and what if he hasn't.

**Comment by thomas-senechal** [comment]
2. Explore the existing libraries we can use to install Thyra automatically

### MacOS:
#### Homebrew: 
Package manager for MacOS and Linux. 

Pros:
- Highly used on MacOS

Cons:
- Not much used in the Linux community 
- Can't controle dependencies versions

Homepage: https://brew.sh/
Build doc: https://docs.brew.sh/Formula-Cookbook
Examples:
- https://github.com/Homebrew/homebrew-cask/blob/master/Casks/google-chrome.rb
- https://github.com/Homebrew/homebrew-core/blob/master/Formula/yasm.rb

### Linux:
#### Flatpak:
Package manager for Linux. Apps are "sandboxed", which means that they are running in a secure virtual sandbox that doesn't require root privileges and can't interact directly with the Linux system, thus eliminating security threats.

Pros:
- Security
- Well-known and liked in the Linux community

Cons:
- Slower than native
- Requires more storage than native since some libraries can be installed multiple times on the system

Build doc: https://docs.flatpak.org/en/latest/

#### Snap:
Package manager created and maintained by Canonical (the company distributing Ubuntu). Installed by default on most Ubuntu based Distros. 

Pros:
- Supported by Canonical and so, installed by default on most Ubuntu based Distros

Cons: 
- Slow, multiple seconds to open an app
- Requires more storage than native and other package manager, mostly because dependencies are not shared between snap apps and so, are downloaded and installed each time it's required
- Disliked by some Linux users because of previous points

Homepage: https://snapcraft.io

#### Appimage:

Pros:
- Near native performances
- Low storage usage
- Easy to uninstall

Cons:
- Bad update management (lacks of updates...)

Homepage: https://appimage.org

#### .deb

Package manager for Debian based distributions (Ubuntu, Linux Mint, Deepin...)

Cons:
- Only works on Debian based distributions

Homepage: https://www.debian.org/doc/debian-policy/index.html

#### .rpm

Package manager for Red Hat based distributions (Fedora, Clear OS, rocky linux, Cent OS...)

Cons:
- Only works on Red Hat based distributions

Homepage: https://rpm.org/documentation.html

### Windows

#### Wix Toolset

Homepage: https://wixtoolset.org

#### Inno Setup

Homepage: https://jrsoftware.org/isinfo.php

### Conclusion

In conclusion:
- Homebrew seems to be the best option for MacOS. 
- The Linux community contains a lot of "power users" that knows how to use terminal and so, should be able to install Thyra by hand, at least in a first time. It is also possible to right a `bash` script to simplify the installation, which would just concatenate the manual installation guide. For the future, using a package manager for Linux would be a nice thing, but the Linux community is kinda divided about that subject and so, picking the right package manager isn't an easy thing. We should discuss about that later to see how package managers evolved in the Linux community to pick the best one fitting our needs and the Massa community needs. 
- For Windows, there are a lot of available options and I think we should spend more time searching for the best option when we will really need that one click install.

There are probably a lot more softwares available to create one click installs, I basically searched for the most known ones and tried to make a listing of pros and cons. This could be improved in the future.

**Comment by gregLibert** [comment]
> The only issue is that it is required me to stop systemd-resolved due to the following error: port 53 already in use.
We could test that running: 
```shell
sudo lsof -i :53
```

**Comment by SlnPons** [comment]
Link to this bug: https://github.com/massalabs/thyra/issues/75

**Comment by SlnPons** [comment]
Based on the result of this investigation, I think we can create 3 issues: 
1. Write a wiki to better explain how to install Thyra manually. We must make it easier for the builder community to install it - https://github.com/massalabs/thyra/issues/108
2. Create installation script for MacOS (trying to see if we can include Linux Ubuntu in the same script)
3. Create installation script for Windows 11
NB: OS version has been decided by looking at the most used version - please challenge before creating the issues if you disagree.
NB2: "Fail Safe" principle will be applied for this installation. It means that we are only going to support very specific OS and communicate on the fact that if users have diff. distribution it will fail and it's normal. The more requests we will have for a specific OS, the more it will become a priority for us.

**Comment by SlnPons** [comment]
@thomas-senechal do you think we can close this issue please?

**Comment by thomas-senechal** [comment]
> do you think we can close this issue please?

I guess we can close this issue since the investigation is done.
